
# PowerShell 5.0 build worker
os: WMF 5

# Secret deployment keys
environment:
  GitHubToken:
    secure: g7atusVu/SvLWa4397EhDExCquI2srCWwO2JetLpnQ57V8Pzm27Eq9kj/v8X6wkd
  PSGalleryKey:
    secure: +o4/iom8ZO0TkCMSM0gInMHq/ioFlK7LRh2jJULTBejba3nCjp2EOv94DcTS2r20

# Install required Pester and PSScriptAnalyzer modules
install:
  - ps: Install-PackageProvider NuGet -Force | Out-Null
  - ps: Install-Module psake -Force
  - ps: Install-Module Pester -Force
  - ps: Install-Module PSScriptAnalyzer -Force

# Set version to build number
version: '{build}'

# Build configuration
configuration: Release
platform: Any CPU

# Execute psake build task
build_script:
  - ps: >-
      Invoke-psake build.psake.ps1 -taskList Build -notr
after_build:
  - ps: >-
      Get-ChildItem -Path 'Releases' -Filter '*.zip' | ForEach-Object { Push-AppveyorArtifact -Path $_.FullName -DeploymentName $_.BaseName -Verbose:$VerbosePreference }

# Execute psake test task
test_script:
  - ps: >-
      Invoke-psake build.psake.ps1 -taskList Test -notr
after_test:
  - ps: >-
      (New-Object -TypeName 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$env:APPVEYOR_JOB_ID", (Resolve-Path -Path 'Tests\pester.xml'))
